#!/bin/sh
#
cpuProfile() {
    case $(cat /sys/firmware/acpi/platform_profile) in
            low-power)
              echo "L "
              ;;
            
            balanced)
              echo "B "
              ;;
            
            performance)
              echo "P "
              ;;
            
            *)
              echo "? "
              ;;
    esac
}

# get info from cpu
speed=$(cpupower frequency-info| grep current.*CPU.*Hz | awk '{print $4}')
profile=$(cpuProfile)
echo "$profile @ $speed GHz"

