#!/bin/sh
#
cpuProfile() {
    case $(cat /sys/firmware/acpi/platform_profile) in
            low-power)
              echo "Low"
              ;;
            
            balanced)
              echo "Bal"
              ;;
            
            performance)
              echo "Per"
              ;;
            
            *)
              echo "???"
              ;;
    esac
}

# get info from cpu
speed=$(cpupower frequency-info| grep current.*CPU.*Hz | awk '{print $4 " " $5}')
profile=$(cpuProfile)
echo "$profile @ $speed"

