USE_POWERLINE="true"

# Source manjaro zsh config
if [[ -e /usr/share/zsh/manjaro-zsh-config ]]; then
  source /usr/share/zsh/manjaro-zsh-config
fi

# Source zsh config files
for file in ~/.config/zsh/* 
do
	source $file
done

# Load starship
eval "$(starship init zsh)"

# Fortune cookie
fortune | lolcat

